services:
  web:
    image: ${DOCKERHUB_USERNAME}/mypetsvoice:latest
    container_name: mypetsvoice-app
    ports:
      - "5000:5000"
    env_file:
      - ../../.env.production
    volumes:
      # 업로드 파일 저장
      - ../../uploads:/app/app/static/uploads
      # 벡터 DB 저장 (영구 저장)
      - ../../vector_db:/app/vector_db
      # RAG 데이터 (읽기 전용) - storage를 /app/storage로 마운트  
      - ../../storage:/app/storage:ro
      # 로그 저장
      - ../../logs:/app/logs
      # Static 파일 공유
      - static_files:/app/app/static
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    networks:
      - mypetsvoice-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: mypetsvoice-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ../../ssl:/etc/nginx/ssl:ro
      - ../../uploads:/app/app/static/uploads:ro
      - static_files:/app/app/static:ro
    depends_on:
      web:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mypetsvoice-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mypetsvoice-network:
    driver: bridge

# 영구 저장이 필요한 데이터를 위한 볼륨 정의
volumes:
  vector_db:
    driver: local
  uploads:
    driver: local
  logs:
    driver: local
  static_files:
    driver: local